@startuml
'https://plantuml.com/class-diagram

class IndexHtml{
createFile()
WriteToFile()
}
class PathGeneration{
websiteBase()
websiteFolder()
cssFolder()
jsFolder()
IndexHtml()
}


PathGeneration <|-- IndexHtml




@enduml