@startuml
'https://plantuml.com/class-diagram

class ReadFile{
Read()
}
class TextReplacer{
useReplacer()
}
class WriteFile{
CreateFile()
WriteFile()
}



TextReplacer <|-- ReadFile
WriteFile <|-- TextReplacer




@enduml